services:
  - type: web
    name: sms-ai-service
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-deploy.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4
      - key: CORS_ORIGINS
        sync: false
